# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toystore.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etoystore.proto\"2\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\r\n\x05stock\x18\x03 \x01(\x05\"\x18\n\x08ItemName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0b\x42uyResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x45\n\x08ToyStore\x12\x19\n\x05Query\x12\t.ItemName\x1a\x05.Item\x12\x1e\n\x03\x42uy\x12\t.ItemName\x1a\x0c.BuyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toystore_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=18
  _globals['_ITEM']._serialized_end=68
  _globals['_ITEMNAME']._serialized_start=70
  _globals['_ITEMNAME']._serialized_end=94
  _globals['_BUYRESPONSE']._serialized_start=96
  _globals['_BUYRESPONSE']._serialized_end=125
  _globals['_TOYSTORE']._serialized_start=127
  _globals['_TOYSTORE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
